# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1507364845);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1507364965);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1507364725);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1507365085);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("datareporting.sessions.current.activeTicks", 0);
user_pref("datareporting.sessions.current.firstPaint", 7015);
user_pref("datareporting.sessions.current.main", 2219);
user_pref("datareporting.sessions.current.startTime", "1507364689715");
user_pref("datareporting.sessions.current.totalTime", 10);
user_pref("datareporting.sessions.currentIndex", 2);
user_pref("datareporting.sessions.previous.1", "{\"s\":1507098906392,\"a\":1,\"t\":9,\"c\":true,\"m\":968,\"fp\":4542,\"sr\":-1}");
user_pref("datareporting.sessions.prunedIndex", 0);
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.bootstrappedAddons", "{\"langpack-en-GB@thunderbird.mozilla.org\":{\"version\":\"52.2.1\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/thunderbird/extensions/langpack-en-GB@thunderbird.mozilla.org.xpi\",\"multiprocessCompatible\":false,\"runInSafeMode\":false,\"dependencies\":[],\"hasEmbeddedWebExtension\":false}}");
user_pref("extensions.databaseSchema", 19);
user_pref("extensions.e10s.rollout.hasAddon", false);
user_pref("extensions.e10sBlockedByAddons", true);
user_pref("extensions.enabledAddons", "messagingmenu%40mozilla.com:1.3.1,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:52.2.1");
user_pref("extensions.getAddons.cache.lastUpdate", 1507364848);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "52.2.1");
user_pref("extensions.lastPlatformVersion", "52.2.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.xpiState", "{\"app-global\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib/thunderbird/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi\",\"e\":true,\"v\":\"52.2.1\",\"st\":1498489881000},\"messagingmenu@mozilla.com\":{\"d\":\"/usr/lib/thunderbird/extensions/messagingmenu@mozilla.com.xpi\",\"e\":true,\"v\":\"1.3.1\",\"st\":1498489844000},\"langpack-en-GB@thunderbird.mozilla.org\":{\"d\":\"/usr/lib/thunderbird/extensions/langpack-en-GB@thunderbird.mozilla.org.xpi\",\"e\":true,\"v\":\"52.2.1\",\"st\":1498490523000}}}");
user_pref("idle.lastDailyNotification", 1507366420);
user_pref("mail.ui-rdf.version", 15);
user_pref("mailnews.database.global.datastore.id", "442f4754-c0e6-4be2-a3b7-f367e2287e3");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.prefsMigrated", true);
user_pref("services.blocklist.addons.checked", 1507338983);
user_pref("services.blocklist.clock_skew_seconds", 25987);
user_pref("services.blocklist.gfx.checked", 1507338983);
user_pref("services.blocklist.last_etag", "\"1492010695571\"");
user_pref("services.blocklist.last_update_seconds", 1507338983);
user_pref("services.blocklist.onecrl.checked", 1507338983);
user_pref("services.blocklist.plugins.checked", 1507338983);
user_pref("storage.vacuum.last.index", 0);
user_pref("toolkit.telemetry.cachedClientID", "0e6d30aa-3a61-4c92-b3ac-4b8de022f59b");
user_pref("toolkit.telemetry.previousBuildID", "20170626135948");
